CREATE TABLE "game_players" (
	"game_id" integer NOT NULL,
	"character_id" integer NOT NULL,
	"team" smallint DEFAULT 0 NOT NULL,
	"ping" integer DEFAULT 0 NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "game_players_game_id_character_id_pk" PRIMARY KEY("game_id","character_id")
);
--> statement-breakpoint
CREATE TABLE "game_rounds" (
	"game_id" integer NOT NULL,
	"character_id" integer NOT NULL,
	CONSTRAINT "game_rounds_game_id_character_id_pk" PRIMARY KEY("game_id","character_id")
);
--> statement-breakpoint
CREATE TABLE "host_reviews" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "host_reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"game_id" integer NOT NULL,
	"host_character_id" integer NOT NULL,
	"voter_character_id" integer NOT NULL,
	"rating" smallint NOT NULL,
	"reviewed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "host_reviews_game_id_voter_character_id_pk" PRIMARY KEY("game_id","voter_character_id")
);
--> statement-breakpoint
ALTER TABLE "game_players" ADD CONSTRAINT "game_players_game_id_games_id_fk" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game_players" ADD CONSTRAINT "game_players_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game_rounds" ADD CONSTRAINT "game_rounds_game_id_games_id_fk" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "game_rounds" ADD CONSTRAINT "game_rounds_character_id_characters_id_fk" FOREIGN KEY ("character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "host_reviews" ADD CONSTRAINT "host_reviews_host_character_id_characters_id_fk" FOREIGN KEY ("host_character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "host_reviews" ADD CONSTRAINT "host_reviews_voter_character_id_characters_id_fk" FOREIGN KEY ("voter_character_id") REFERENCES "public"."characters"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "host_reviews_host_idx" ON "host_reviews" USING btree ("host_character_id","reviewed_at");