apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '10'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"mgo2-gameplay-1","namespace":"mgo2"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mgo2-gameplay-1"}},"template":{"metadata":{"labels":{"app":"mgo2-gameplay-1"}},"spec":{"containers":[{"env":[{"name":"GAMEPLAY_SERVER_PORT","value":"5730"},{"name":"GAMEPLAY_SERVER_LOBBY_NAME","value":"Free
      Battle"}],"image":"ghcr.io/miguelripoll23/mgo2-server/mgo2-gameplay-server:latest","name":"gameplay","ports":[{"containerPort":5730,"protocol":"UDP"}],"readinessProbe":{"exec":{"command":["/bin/sh","-c","timeout
      2 bash -c ''echo \u003e /dev/udp/127.0.0.1/5730''"]},"failureThreshold":3,"initialDelaySeconds":10,"periodSeconds":5},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"add":[],"drop":["ALL"]},"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}},"volumeMounts":[{"mountPath":"/app/appsettings.json","name":"appsettings","readOnly":true,"subPath":"appsettings.json"}]}],"terminationGracePeriodSeconds":21600,"volumes":[{"configMap":{"name":"mgo2-appsettings"},"name":"appsettings"}]}}}}

      '
  creationTimestamp: '2026-09-19T01:05:10Z'
  generation: 10
  name: mgo2-gameplay-1
  namespace: mgo2
  resourceVersion: '24820'
  uid: 0ca0b587-95e0-4d64-b7a5-d6716b0862b9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mgo2-gameplay-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-09-19T04:45:15+02:00'
      labels:
        app: mgo2-gameplay-1
    spec:
      containers:
      - env:
        - name: GAMEPLAY_SERVER_PORT
          value: '5730'
        - name: GAMEPLAY_SERVER_LOBBY_NAME
          value: Free Battle
        image: ghcr.io/miguelripoll23/mgo2-server/mgo2-gameplay-server:latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - sleep 5
        name: gameplay
        ports:
        - containerPort: 5730
          protocol: UDP
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - timeout 2 bash -c 'echo > /dev/udp/127.0.0.1/5730'
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/appsettings.json
          name: appsettings
          readOnly: true
          subPath: appsettings.json
        envFrom:
        - secretRef:
            name: mgo2-secrets
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 21600
      volumes:
      - name: appsettings
        configMap:
          name: mgo2-appsettings
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: '2026-09-19T01:05:33Z'
    lastUpdateTime: '2026-09-19T01:05:33Z'
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: 'True'
    type: Available
  - lastTransitionTime: '2026-09-19T11:09:01Z'
    lastUpdateTime: '2026-09-19T11:24:58Z'
    message: ReplicaSet "mgo2-gameplay-1-5cb7cc4b54" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: 'True'
    type: Progressing
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  terminatingReplicas: 0
  updatedReplicas: 1
