apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '11'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"mgo2-http","namespace":"mgo2"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mgo2-http"}},"template":{"metadata":{"labels":{"app":"mgo2-http"}},"spec":{"containers":[{"image":"ghcr.io/miguelripoll23/mgo2-server/mgo2-http:latest","name":"http","ports":[{"containerPort":80,"protocol":"TCP"}],"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["ALL"]},"runAsNonRoot":true,"runAsUser":1000,"seccompProfile":{"type":"RuntimeDefault"}},"volumeMounts":[{"mountPath":"/app/appsettings.json","name":"appsettings","readOnly":true,"subPath":"appsettings.json"},{"mountPath":"/root/.aspnet/DataProtection-Keys","name":"http-keys"}]}],"volumes":[{"configMap":{"name":"mgo2-appsettings"},"name":"appsettings"},{"emptyDir":{},"name":"http-keys"}]}}}}

      '
  creationTimestamp: '2026-09-19T01:05:10Z'
  generation: 11
  name: mgo2-http
  namespace: mgo2
  resourceVersion: '24978'
  uid: 11c1773e-4920-404c-af93-1200330dd58e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mgo2-http
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2026-09-19T04:45:16+02:00'
      labels:
        app: mgo2-http
    spec:
      containers:
      - image: ghcr.io/miguelripoll23/mgo2-server/mgo2-http:latest
        imagePullPolicy: Always
        name: http
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 5743
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/appsettings.json
          name: appsettings
          readOnly: true
          subPath: appsettings.json
        - mountPath: /root/.aspnet/DataProtection-Keys
          name: http-keys
        envFrom:
        - secretRef:
            name: mgo2-secrets
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: appsettings
        configMap:
          name: mgo2-appsettings
      - emptyDir: {}
        name: http-keys
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: '2026-09-19T01:05:33Z'
    lastUpdateTime: '2026-09-19T01:05:33Z'
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: 'True'
    type: Available
  - lastTransitionTime: '2026-09-19T01:05:10Z'
    lastUpdateTime: '2026-09-19T11:24:42Z'
    message: ReplicaSet "mgo2-http-6bcc684957" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: 'True'
    type: Progressing
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  terminatingReplicas: 0
  updatedReplicas: 1
