apiVersion: v1
kind: Service
metadata:
  name: mgo2-dns
  namespace: mgo2
spec:
  clusterIP: 10.43.60.47
  clusterIPs:
  - 10.43.60.47
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: mgo2-dns
  sessionAffinity: None
  type: ClusterIP
