apiVersion: v1
kind: Service
metadata:
  name: mgo2-gameplay-1
  namespace: mgo2
spec:
  clusterIP: 10.43.164.182
  clusterIPs:
  - 10.43.164.182
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5730
    protocol: UDP
    targetPort: 5730
  selector:
    app: mgo2-gameplay-1
  sessionAffinity: None
  type: ClusterIP
