apiVersion: v1
kind: Service
metadata:
  name: mgo2-survival
  namespace: mgo2
spec:
  clusterIP: 10.43.40.21
  clusterIPs:
  - 10.43.40.21
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5735
    protocol: TCP
    targetPort: 5735
  selector:
    app: mgo2-survival
  sessionAffinity: None
  type: ClusterIP
