using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mgo2Server.Shared.Persistence.Entities;

/// <summary>
/// A single host-rating vote. Votes are history and outlive the game, so they
/// are appended rather than accumulated onto the game row. One vote per player
/// per game.
/// </summary>
[Table("host_reviews")]
public sealed class HostReview
{
    /// <summary>Identifier of the review, generated by default as identity.</summary>
    [Column("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Identifier { get; set; }

    /// <summary>Room the vote was cast in.</summary>
    [Column("game_id")]
    public int GameIdentifier { get; set; }

    /// <summary>Character that was hosting.</summary>
    [Column("host_character_id")]
    public int HostCharacterIdentifier { get; set; }

    /// <summary>Character that cast the vote.</summary>
    [Column("voter_character_id")]
    public int VoterCharacterIdentifier { get; set; }

    /// <summary>Star rating the voter awarded.</summary>
    [Column("rating")]
    public short Rating { get; set; }

    /// <summary>Timestamp with time zone the vote was cast at.</summary>
    [Column("reviewed_at")]
    public DateTimeOffset ReviewedAt { get; set; }

    /// <summary>Hosting character.</summary>
    [ForeignKey(nameof(HostCharacterIdentifier))]
    public Character? Host { get; set; }

    /// <summary>Character that cast the vote.</summary>
    [ForeignKey(nameof(VoterCharacterIdentifier))]
    public Character? Voter { get; set; }
}

/// <summary>
/// One host-reported round statistics frame, the source of the match history.
/// The game row is deleted at teardown, so the report carries its own lobby
/// subtype for the type label.
/// </summary>
[Table("round_reports")]
public sealed class RoundReport
{
    /// <summary>Identifier of the report.</summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column("id")]
    public int Identifier { get; set; }

    /// <summary>Room the round was played in.</summary>
    [Column("game_id")]
    public int GameIdentifier { get; set; }

    /// <summary>Character that hosted the round.</summary>
    [Column("host_character_id")]
    public int HostCharacterIdentifier { get; set; }

    /// <summary>Character the report describes.</summary>
    [Column("target_character_id")]
    public int TargetCharacterIdentifier { get; set; }

    /// <summary>Team the report credits with the win.</summary>
    [Column("team_win")]
    public short TeamWin { get; set; }

    /// <summary>Duration of the round in seconds.</summary>
    [Column("seconds")]
    public int Seconds { get; set; }

    /// <summary>Experience awarded by the round.</summary>
    [Column("experience")]
    public int Experience { get; set; }

    /// <summary>Whether the round was aborted.</summary>
    [Column("aborted")]
    public bool Aborted { get; set; }

    /// <summary>Subtype of the lobby the round was played in.</summary>
    [Column("lobby_subtype")]
    public short LobbySubtype { get; set; }

    /// <summary>Timestamp without time zone the report was stored at.</summary>
    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    /// <summary>Room the round was played in.</summary>
    [ForeignKey(nameof(GameIdentifier))]
    public Game? Game { get; set; }

    /// <summary>Hosting character.</summary>
    [ForeignKey(nameof(HostCharacterIdentifier))]
    public Character? Host { get; set; }

    /// <summary>Character the report describes.</summary>
    [ForeignKey(nameof(TargetCharacterIdentifier))]
    public Character? Target { get; set; }
}

/// <summary>End-of-round weapon tallies; stored only, nothing derives from them yet.</summary>
[Table("weapon_tallies")]
public sealed class WeaponTally
{
    /// <summary>Identifier of the row.</summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column("id")]
    public int Identifier { get; set; }

    /// <summary>Room the tally belongs to.</summary>
    [Column("game_id")]
    public int GameIdentifier { get; set; }

    /// <summary>Character the tally belongs to.</summary>
    [Column("character_id")]
    public int CharacterIdentifier { get; set; }

    /// <summary>Weapon identifier.</summary>
    [Column("weapon_id")]
    public short WeaponIdentifier { get; set; }

    /// <summary>First tallied value.</summary>
    [Column("value_a")]
    public short ValueA { get; set; }

    /// <summary>Second tallied value.</summary>
    [Column("value_b")]
    public short ValueB { get; set; }

    /// <summary>Third tallied value.</summary>
    [Column("value_c")]
    public short ValueC { get; set; }

    /// <summary>Room the tally belongs to.</summary>
    [ForeignKey(nameof(GameIdentifier))]
    public Game? Game { get; set; }

    /// <summary>Character the tally belongs to.</summary>
    [ForeignKey(nameof(CharacterIdentifier))]
    public Character? Character { get; set; }
}
