using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mgo2Server.Shared.Persistence.Entities;

/// <summary>
/// A single host-rating vote. Votes are history and outlive the game, so they
/// are appended rather than accumulated onto the game row. One vote per player
/// per game.
/// </summary>
[Table("host_reviews")]
public sealed class HostReview
{
    /// <summary>Identifier of the review, generated by default as identity.</summary>
    [Column("id")]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Identifier { get; set; }

    /// <summary>Room the vote was cast in.</summary>
    [Column("game_id")]
    public int GameIdentifier { get; set; }

    /// <summary>Character that was hosting.</summary>
    [Column("host_character_id")]
    public int HostCharacterIdentifier { get; set; }

    /// <summary>Character that cast the vote.</summary>
    [Column("voter_character_id")]
    public int VoterCharacterIdentifier { get; set; }

    /// <summary>Star rating the voter awarded.</summary>
    [Column("rating")]
    public short Rating { get; set; }

    /// <summary>Timestamp with time zone the vote was cast at.</summary>
    [Column("reviewed_at")]
    public DateTimeOffset ReviewedAt { get; set; }

    /// <summary>Hosting character.</summary>
    [ForeignKey(nameof(HostCharacterIdentifier))]
    public Character? Host { get; set; }

    /// <summary>Character that cast the vote.</summary>
    [ForeignKey(nameof(VoterCharacterIdentifier))]
    public Character? Voter { get; set; }
}

/// <summary>
/// One host-reported round statistics frame. The frame is stored as it arrived,
/// counter by counter, rather than folded into a per-character accumulator, so
/// every statistics surface derives from it at query time. The game row is deleted
/// at teardown, so the report carries its own lobby subtype and game mode for the
/// labels and the per-mode splits.
/// </summary>
[Table("round_reports")]
public sealed class RoundReport
{
    /// <summary>Identifier of the report.</summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column("id")]
    public int Identifier { get; set; }

    /// <summary>Room the round was played in.</summary>
    [Column("game_id")]
    public int GameIdentifier { get; set; }

    /// <summary>Character that hosted the round.</summary>
    [Column("host_character_id")]
    public int HostCharacterIdentifier { get; set; }

    /// <summary>Character the report describes.</summary>
    [Column("target_character_id")]
    public int TargetCharacterIdentifier { get; set; }

    /// <summary>
    /// Game mode the round was played under, stamped at insert. It cannot be read back
    /// from the room because the room is deleted at teardown while reports are history.
    /// </summary>
    [Column("rule")]
    public short Rule { get; set; }

    /// <summary>Team the report credits with the win.</summary>
    [Column("team_win")]
    public short TeamWin { get; set; }

    /// <summary>Duration of the round in seconds.</summary>
    [Column("seconds")]
    public int Seconds { get; set; }

    /// <summary>Experience awarded by the round.</summary>
    [Column("experience")]
    public int Experience { get; set; }

    /// <summary>Whether the round was aborted.</summary>
    [Column("aborted")]
    public bool Aborted { get; set; }

    /// <summary>Subtype of the lobby the round was played in.</summary>
    [Column("lobby_subtype")]
    public short LobbySubtype { get; set; }

    /// <summary>Rounds won within the round's frame.</summary>
    [Column("wins")]
    public short Wins { get; set; }

    /// <summary>Kills.</summary>
    [Column("kills")]
    public short Kills { get; set; }

    /// <summary>Deaths.</summary>
    [Column("deaths")]
    public short Deaths { get; set; }

    /// <summary>Score earned, signed because deaths and penalties outweigh kills.</summary>
    [Column("score")]
    public short Score { get; set; }

    /// <summary>Stuns delivered.</summary>
    [Column("stuns")]
    public short Stuns { get; set; }

    /// <summary>Stuns received.</summary>
    [Column("stuns_received")]
    public short StunsReceived { get; set; }

    /// <summary>Headshot kills.</summary>
    [Column("headshot_kills")]
    public short HeadshotKills { get; set; }

    /// <summary>Headshot deaths.</summary>
    [Column("headshot_deaths")]
    public short HeadshotDeaths { get; set; }

    /// <summary>Headshot stuns delivered.</summary>
    [Column("headshot_stuns")]
    public short HeadshotStuns { get; set; }

    /// <summary>Headshot stuns received.</summary>
    [Column("headshot_stuns_received")]
    public short HeadshotStunsReceived { get; set; }

    /// <summary>Lock-on kills.</summary>
    [Column("lock_kills")]
    public short LockKills { get; set; }

    /// <summary>Lock-on deaths.</summary>
    [Column("lock_deaths")]
    public short LockDeaths { get; set; }

    /// <summary>Lock-on stuns delivered.</summary>
    [Column("lock_stuns")]
    public short LockStuns { get; set; }

    /// <summary>Lock-on stuns received.</summary>
    [Column("lock_stuns_received")]
    public short LockStunsReceived { get; set; }

    /// <summary>Best consecutive kill streak of the round.</summary>
    [Column("consecutive_kills")]
    public short ConsecutiveKills { get; set; }

    /// <summary>Timestamp with time zone the report was stored at.</summary>
    [Column("created_at")]
    public DateTimeOffset CreatedAt { get; set; }

    /// <summary>Room the round was played in.</summary>
    [ForeignKey(nameof(GameIdentifier))]
    public Game? Game { get; set; }

    /// <summary>Hosting character.</summary>
    [ForeignKey(nameof(HostCharacterIdentifier))]
    public Character? Host { get; set; }

    /// <summary>Character the report describes.</summary>
    [ForeignKey(nameof(TargetCharacterIdentifier))]
    public Character? Target { get; set; }
}

/// <summary>End-of-round per-weapon statistics; stored only, nothing derives from them yet.</summary>
[Table("round_weapon_stats")]
public sealed class RoundWeaponStat
{
    /// <summary>Identifier of the row.</summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column("id")]
    public int Identifier { get; set; }

    /// <summary>Room the statistic belongs to.</summary>
    [Column("game_id")]
    public int GameIdentifier { get; set; }

    /// <summary>Character the statistic belongs to.</summary>
    [Column("character_id")]
    public int CharacterIdentifier { get; set; }

    /// <summary>Weapon identifier.</summary>
    [Column("weapon_id")]
    public short WeaponIdentifier { get; set; }

    /// <summary>Kills credited to the weapon.</summary>
    [Column("kills")]
    public short Kills { get; set; }

    /// <summary>Headshots the weapon ended kills or faints with.</summary>
    [Column("headshots")]
    public short Headshots { get; set; }

    /// <summary>Faints the weapon caused.</summary>
    [Column("faints")]
    public short Faints { get; set; }

    /// <summary>Timestamp with time zone the statistic was reported at.</summary>
    [Column("reported_at")]
    public DateTimeOffset ReportedAt { get; set; }

    /// <summary>Room the statistic belongs to.</summary>
    [ForeignKey(nameof(GameIdentifier))]
    public Game? Game { get; set; }

    /// <summary>Character the statistic belongs to.</summary>
    [ForeignKey(nameof(CharacterIdentifier))]
    public Character? Character { get; set; }
}
