<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Mgo2Server.Stun</RootNamespace>
    <OutputType>Exe</OutputType>
    <AssemblyName>Mgo2Server.Stun</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Mgo2Server.Shared.csproj" />
  </ItemGroup>

</Project>
